apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erpnext
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem