apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: erpnext
  name: new-site
spec:
  manualSelector: true
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 7ad3a326-78c1-4613-b9b8-96e2799c213e
  suspend: false
  template:
    spec:
      containers:
      - args:
        - |
          bench new-site $(SITE_NAME) --db-type=$(DB_TYPE) --db-host=$(DB_HOST) --db-port=$(DB_PORT) --admin-password=$(ADMIN_PASSWORD) --mariadb-root-username=$(DB_ROOT_USER) --mariadb-root-password=$(DB_ROOT_PASSWORD) --install-app=erpnext --force ;rm -f currentsite.txt
        command:
        - bash
        - -c
        env:
        - name: SITE_NAME
          value: localhost
        - name: DB_TYPE
          value: mariadb
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        - name: DB_ROOT_USER
          value: root
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: mariadb
        - name: ADMIN_PASSWORD
          value: praktis2022
        image: frappe/erpnext-worker:v13.32.0
        imagePullPolicy: IfNotPresent
        name: create-site
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: sites-dir
        - mountPath: /home/frappe/frappe-bench/sites/assets
          name: assets-cache
        - mountPath: /home/frappe/frappe-bench/logs
          name: logs
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - /usr/share/nginx/html/assets
        - /home/frappe/frappe-bench/sites
        command:
        - cp
        - -fR
        image: frappe/erpnext-nginx:v13.32.0
        imagePullPolicy: IfNotPresent
        name: populate-assets
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites/assets
          name: assets-cache
      - args:
        - |
          export start=`date +%s`; until [[ -n `grep -hs ^ common_site_config.json | jq -r ".db_host // empty"` ]] && \
            [[ -n `grep -hs ^ common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
            [[ -n `grep -hs ^ common_site_config.json | jq -r ".redis_queue // empty"` ]];
          do
            echo "Waiting for common_site_config.json to be created";
            sleep 5;
            if (( `date +%s`-start > 600 )); then
              echo "could not find common_site_config.json with required keys";
              exit 1
            fi
          done; echo "common_site_config.json found";
        command:
        - bash
        - -c
        image: frappe/erpnext-worker:v13.32.0
        imagePullPolicy: IfNotPresent
        name: validate-config
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: sites-dir
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 1000
      serviceAccount: erpnext
      serviceAccountName: erpnext
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: assets-cache
      - name: sites-dir
        persistentVolumeClaim:
          claimName: erpnext
      - name: logs
        persistentVolumeClaim:
          claimName: erpnext-logs