apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/version: v13.32.0
  name: gunicorn
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: gunicorn
  sessionAffinity: None
  type: ClusterIP