apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/name: erpnext
  name: erpnext
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx
  sessionAffinity: None
  type: ClusterIP