apiVersion: batch/v1
kind: Job
metadata:
  name: job-new-site
  namespace: frapper
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
        - name: populate-assets
          image: frappe/erpnext-nginx:v13.32.0
          imagePullPolicy: IfNotPresent
          command:
            - cp
            - -fR
          args:
            - /usr/share/nginx/html/assets
            - /home/frappe/frappe-bench/sites
          volumeMounts:
            - name: assets-cache
              mountPath: /home/frappe/frappe-bench/sites/assets
        - name: validate-config
          image: frappe/erpnext-worker:v13.32.0
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - >
              export start=`date +%s`;
              until [[ -n `grep -hs ^ common_site_config.json | jq -r ".db_host // empty"` ]] && \
                [[ -n `grep -hs ^ common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
                [[ -n `grep -hs ^ common_site_config.json | jq -r ".redis_queue // empty"` ]];
              do
                echo "Waiting for common_site_config.json to be created";
                sleep 5;
                if (( `date +%s`-start > 600 )); then
                  echo "could not find common_site_config.json with required keys";
                  exit 1
                fi
              done;
              echo "common_site_config.json found";
          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
      containers:
      - name: create-site
        image: frappe/erpnext-worker:v13.32.0
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - >
            bench new-site $(SITE_NAME)
            --db-type=$(DB_TYPE)
            --db-host=$(DB_HOST)
            --db-port=$(DB_PORT)
            --admin-password=$(ADMIN_PASSWORD)
            --mariadb-root-username=$(DB_ROOT_USER)
            --mariadb-root-password=$(DB_ROOT_PASSWORD)
            --install-app=erpnext
            --force
            ;rm -f currentsite.txt
        env:
          - name: "SITE_NAME"
            value: localhost
          - name: "DB_TYPE"
            value: "mariadb"
          - name: "DB_HOST"
            value: "mariadb.frapper.svc.cluster.local"
          - name: "DB_PORT"
            value: "3306"
          - name: "DB_ROOT_USER"
            value: praktis
          - name: "DB_ROOT_PASSWORD"
            value: praktis2022
          - name: "ADMIN_PASSWORD"
            value: praktis2022
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: assets-cache
            mountPath: /home/frappe/frappe-bench/sites/assets
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: assets-cache
        - name: sites-dir
          persistentVolumeClaim:
            claimName: frappe-data
            readOnly: false
        - name: logs
          persistentVolumeClaim:
            claimName: frappe-logs
            readOnly: false
