kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frappe-data
  namespace: frapper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard