apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: frapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
      app.kubernetes.io/instance: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
        app.kubernetes.io/instance: scheduler
    spec:
      containers:
        - name: scheduler
          args:
          - bench
          - schedule
          image: frappe/erpnext-worker:v13.32.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: frappe-data
            readOnly: false
        - name: logs
          persistentVolumeClaim:
            claimName: frappe-logs
