apiVersion: v1
kind: Service
metadata:
  name: socketio
  namespace: frapper
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: socketio
    app.kubernetes.io/instance: socketio
