apiVersion: v1
kind: Service
metadata:
  name: frappe-gunicorn
  namespace: frapper
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gunicorn
    app.kubernetes.io/instance: gunicorn
