apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-default
  namespace: frapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker-default
      app.kubernetes.io/instance: worker-default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker-default
        app.kubernetes.io/instance: worker-default
    spec:
      containers:
        - name: worker-default
          args:
          - bench
          - worker
          - --queue
          - default
          image: frappe/erpnext-worker:v13.32.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: frappe-data
            readOnly: false
        - name: logs
          persistentVolumeClaim:
            claimName: frappe-logs
            readOnly: false