apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/component: primary
    app.kubernetes.io/name: mariadb
  name: mariadb
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/name: mariadb
  sessionAffinity: None
  type: ClusterIP